[placeholders]
"service_description" = { type = "string", prompt = "Enter a brief description of the service:", default = "Default Service Description" }
"rpc_method" = { type = "string", prompt = "Enter the RPC method name:", default = "make" }

[template]
include = ["src/**/*", "Cargo.toml", "proto/**/*", "build.rs"]

[hooks]
pre_gen_command = "echo 'Preparing to generate the service...'"
post_gen_command = "echo 'Service generation complete!'"