[placeholders]
"service_description" = { type = "string", prompt = "Enter a brief description of the service:" }

[template]
include = ["src/**/*", "Cargo.toml", "proto/**/*", "build.rs"]

[hooks]
pre_gen_command = "echo 'Preparing to generate the service...'"
post_gen_command = "echo 'Service generation complete!'"